services:
  db:
    image: postgres:17
    container_name: hexapi-db-${ENV}
    restart: always
    environment:
      POSTGRES_DB: ${BDD_NAME}
      POSTGRES_USER: ${BDD_USER}
      POSTGRES_PASSWORD: ${BDD_PASSWORD}
    volumes:
      - db_data_preprod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  back:
    image: ghcr.io/baptiste-ferrand/hexagonal-api:${ENV}
    container_name: hexapi-app-${ENV}
    restart: always
    ports:
      - "${NGINX_PORT}:8000"
    env_file:
      - .env

volumes:
  db_data_preprod:
